Repository Dansoftowner/14AB-A-plander-frontend, pull requests merged in 2024-02, with the labels that each got.

#65 ✨ Assignments
  ACKNOWLEDGEMENTS.md
  package-lock.json
  package.json
  src/components/Assignments/AddAssignment.tsx
  src/components/Assignments/Assignments.tsx
  src/components/Assignments/CalendarComponent.tsx
  src/components/Assignments/calendar.css
  src/components/Assignments/utils.ts
  src/components/Layout.tsx
  src/components/LoginPage/LoginPage.tsx
  src/components/NavBar/NavBar.tsx
  src/hooks/hooks.ts
  src/hooks/useAssignments.ts
  src/hooks/useMembers.ts
  src/i18n.ts
  src/locales/en/assignments.json
  src/locales/en/login.json
  src/locales/en/member.json
  src/locales/en/register.json
  src/locales/en/translation.json
  src/locales/hu/assignments.json
  src/locales/hu/login.json
  src/locales/hu/member.json
  src/locales/hu/register.json
  src/locales/hu/translation.json
  src/routes.tsx
Labels: enhancement, frontend

#69 🚑 Login error fixed
  src/components/LoginPage/LoginPage.tsx
Labels: bug, enhancement, frontend

#70 :bug: Fix registration error
  src/components/LoginPage/LoginPage.tsx
  src/components/RegisterForm/RegisterForm.tsx
  src/components/RegisterForm/inputSchema.tsx
Labels: bug, frontend

#71 ✨ Member's detail re-design
  src/components/MemberDetail/MemberDetail.tsx
  src/components/PhoneDropdownList/PhoneDropdownList.tsx
  src/components/RegisterForm/FormInput.tsx
  src/components/RegisterForm/specInputHandler.ts
  src/hooks/hooks.ts
  src/hooks/useCredentials.ts
  src/hooks/useMembers.ts
Labels: enhancement, frontend

#76 Design fix
  package-lock.json
  package.json
  src/components/Layout.tsx
  src/components/LoginPage/LoginPage.tsx
  src/components/MemberDetail/MemberDetail.tsx
  src/components/MembersList/InviteMember.tsx
  src/components/NavBar/NavBar.tsx
  src/components/PhoneDropdownList/PhoneDropdownList.tsx
  src/components/RegisterForm/FormInput.tsx
  src/components/RegisterForm/PasswordInput.tsx
  src/hooks/useMembers.ts
  src/locales/en/register.json
  src/locales/hu/register.json
Labels: enhancement, frontend

#81 Deploy
  .eslintrc.cjs
  src/components/Assignments/AddAssignment.tsx
  src/components/Assignments/Assignments.tsx
  src/components/Assignments/CalendarComponent.tsx
  src/components/ErrorPage/ErrorPage.tsx
  src/components/ForgotPassword/ForgotPassword.tsx
  src/components/LoginPage/LoginPage.tsx
  src/components/MembersList/MembersList.tsx
  src/components/NavBar/NavBar.tsx
  src/components/RegisterForm/PasswordInput.tsx
  src/hooks/useMembers.ts
  tsconfig.json
Labels: enhancement, frontend

#82 Reports
  .eslintrc.cjs
  src/components/Assignments/AddAssignment.tsx
  src/components/Assignments/Assignments.tsx
  src/components/Assignments/CalendarComponent.tsx
  src/components/ErrorPage/ErrorPage.tsx
  src/components/ForgotPassword/ForgotPassword.tsx
  src/components/Layout.tsx
  src/components/LoginPage/LoginPage.tsx
  src/components/MemberDetail/MemberDetail.tsx
  src/components/MembersList/MembersList.tsx
  src/components/NavBar/NavBar.tsx
  src/components/RegisterForm/PasswordInput.tsx
  src/components/Reports/ReportDetail.tsx
  src/components/Reports/Reports.tsx
  src/hooks/hooks.ts
  src/hooks/useAssignments.ts
  src/hooks/useMembers.ts
  src/hooks/useReports.ts
  src/locales/en/translation.json
  src/locales/hu/translation.json
  src/routes.tsx
  tsconfig.json
Labels: frontend

#85 Implemented report functions
  src/components/Assignments/Assignments.tsx
  src/components/Assignments/CalendarComponent.tsx
  src/components/MemberDetail/MemberDetail.tsx
  src/components/RegisterForm/FormInput.tsx
  src/components/RegisterForm/RegisterForm.tsx
  src/components/Reports/ReportDetail.tsx
  src/components/Reports/Reports.tsx
  src/hooks/useReports.ts
  src/hooks/useTransfer.ts
  src/locales/en/assignments.json
  src/locales/hu/assignments.json
Labels: enhancement, frontend

#88 Vercel routing fix
  src/hooks/useReports.ts
  src/routes.tsx
Labels: frontend

#93 Chats
  ACKNOWLEDGEMENTS.md
  package-lock.json
  package.json
  src/components/Chats/ChatBox.tsx
  src/components/Chats/Message.tsx
  src/components/HomePage/HomePage.tsx
  src/components/MemberDetail/MemberDetail.tsx
  src/services/socket.ts
Labels: enhancement, frontend

#94 :bug: Socket insecure connection
  src/services/socket.ts
Labels: bug, frontend

#95 :bug: Fixed insecure connection
  src/services/socket.ts
Labels: frontend

#104 ✨ Fully functional chat
  ACKNOWLEDGEMENTS.md
  package-lock.json
  package.json
  src/components/Chats/ChatBox.tsx
  src/components/Chats/Message.tsx
  src/components/HomePage/HomePage.tsx
  src/components/Layout.tsx
  src/components/NavBar/NavBar.tsx
  src/context/authContext.ts
  src/hooks/useChats.ts
  src/locales/en/translation.json
  src/locales/hu/translation.json
  src/services/socket.ts
Labels: enhancement, frontend

#108 Preferences
  src/components/Chats/ChatBox.tsx
  src/components/Chats/Message.tsx
  src/components/ColorModeSwitch.tsx
  src/components/LangSelector.tsx
  src/components/Layout.tsx
  src/components/Reports/ReportDetail.tsx
  src/context/authContext.ts
  src/hooks/hooks.ts
  src/hooks/usePreferences.ts
Labels: frontend

#109 💄 UI update on members list
  src/components/MemberCard/MemberCard.tsx
  src/components/MembersList/MembersList.tsx
  src/hooks/useMembers.ts
Labels: frontend

#110 🐛 Fixed member deletion and added missing translation
  src/components/MemberCard/MemberCard.tsx
  src/components/MembersList/InviteMember.tsx
  src/locales/en/member.json
  src/locales/hu/member.json
Labels: bug, enhancement, frontend

#116 Beta fixes
  src/App.css
  src/components/Assignments/Assignments.tsx
  src/components/Assignments/CalendarComponent.tsx
  src/components/Chats/ChatBox.tsx
  src/components/Chats/Message.tsx
  src/components/HomePage/HomePage.tsx
  src/components/LoginPage/LoginPage.tsx
  src/components/MembersList/InviteMember.tsx
  src/components/MembersList/MembersList.tsx
  src/components/RegisterForm/PasswordInput.tsx
Labels: enhancement, frontend

#118 V1.0.1
  src/App.css
  src/components/Assignments/Assignments.tsx
  src/components/Assignments/CalendarComponent.tsx
  src/components/Chats/ChatBox.tsx
  src/components/Chats/Message.tsx
  src/components/HomePage/HomePage.tsx
  src/components/LoginPage/LoginPage.tsx
  src/components/MembersList/InviteMember.tsx
  src/components/MembersList/MembersList.tsx
  src/components/RegisterForm/PasswordInput.tsx
Labels: enhancement, frontend

#123 V1.1.1
  src/components/Assignments/Assignments.tsx
  src/components/Assignments/CalendarComponent.tsx
  src/components/HomePage/HomePage.tsx
  src/components/MemberDetail/MemberDetail.tsx
  src/components/MembersList/InviteMember.tsx
  src/components/RegisterForm/inputSchema.tsx
  src/components/Reports/ReportDetail.tsx
  src/hooks/useAssignments.ts
  src/hooks/useChats.ts
  src/hooks/useReports.ts
  src/locales/en/assignments.json
  src/locales/hu/assignments.json
Labels: enhancement, frontend

#124 ✨ V1.1.1
  src/components/Assignments/Assignments.tsx
  src/components/Assignments/CalendarComponent.tsx
  src/components/HomePage/HomePage.tsx
  src/components/MemberDetail/MemberDetail.tsx
  src/components/MembersList/InviteMember.tsx
  src/components/RegisterForm/inputSchema.tsx
  src/components/Reports/ReportDetail.tsx
  src/hooks/useAssignments.ts
  src/hooks/useChats.ts
  src/hooks/useReports.ts
  src/locales/en/assignments.json
  src/locales/hu/assignments.json
Labels: frontend

#126 🔐 Env variables added
  .gitignore
  src/components/Chats/Chat.tsx
  src/services/apiClient.ts
Labels: frontend

#127 v1.1.2
  .gitignore
  src/components/Chats/Chat.tsx
  src/services/apiClient.ts
Labels: enhancement, frontend

#128 🐛 Invalid env fixed
  package-lock.json
  package.json
  vite.config.ts
Labels: bug, frontend

#129 V1.1.3
  package-lock.json
  package.json
  vite.config.ts
Labels: bug, enhancement, frontend

#130 Adjusted visual elements
  index.html
  src/components/Assignments/AddAssignment.tsx
  src/components/Chats/ChatBox.tsx
  src/components/LoginPage/LoginPage.tsx
  src/components/MemberCard/MemberCard.tsx
  src/components/MembersList/InviteMember.tsx
  src/locales/en/register.json
  src/locales/en/translation.json
  src/locales/hu/login.json
  src/locales/hu/register.json
  src/locales/hu/translation.json
Labels: enhancement, frontend

#133 :lipstick: Added loader to PDF export
  src/components/Assignments/CalendarComponent.tsx
Labels: frontend

#134 V1.1.3 Visual changes
  index.html
  src/components/Assignments/AddAssignment.tsx
  src/components/Assignments/CalendarComponent.tsx
  src/components/Chats/ChatBox.tsx
  src/components/LoginPage/LoginPage.tsx
  src/components/MemberCard/MemberCard.tsx
  src/components/MembersList/InviteMember.tsx
  src/locales/en/register.json
  src/locales/en/translation.json
  src/locales/hu/login.json
  src/locales/hu/register.json
  src/locales/hu/translation.json
Labels: enhancement, frontend

#135 :children_crossing: feedback update
  src/components/RegisterForm/RegisterForm.tsx
Labels: frontend

#137 Feedback and validation changes
  src/components/MemberDetail/MemberDetail.tsx
  src/components/MemberDetail/utils.ts
  src/components/RegisterForm/RegisterForm.tsx
  src/components/RegisterForm/inputSchema.tsx
Labels: frontend

#140 ✅ Added cypress E2E test
  cypress.config.ts
  cypress/e2e/login.cy.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  package-lock.json
  package.json
  src/components/LoginPage/LoginPage.tsx
  tsconfig.json
Labels: enhancement, frontend
